# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd = {
      availableKernelModules =
        [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" ];
      kernelModules = [ "dm-snapshot" ];
      luks.devices = {
        encrypted = {
          device = "/dev/disk/by-uuid/f23d6240-95e2-40e8-841d-553137912d48";
          preLVM = true;
        };
      };
    };
    kernelModules = [ "kvm-intel" ];
    kernelParams = [
      "resume_offset=13768704"
      "processor.max_cstate=4"
      "amd_iomu=soft"
      "idle=nomwait"
    ];
    kernelPackages = pkgs.linuxPackages_latest;

    extraModulePackages = [ ];
    resumeDevice = "/dev/mapper/vg-root";
  };
  powerManagement.enable = true;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b8ec04cc-a11e-4b78-b570-22fc9e4ac6f0";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0839-55A6";
    fsType = "vfat";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/f69c7a30-b598-46f2-85c3-b8a2c19dc3a8"; }
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024;
    }
  ];

  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.opengl.driSupport32Bit = true;
  hardware.opengl.enable = true;
  hardware.pulseaudio.support32Bit = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
